### PR TITLE
Change Artists list behavior

### PR DESCRIPTION
**Pull request by darkguinito**
Modifying artist request to supply complete artist list
Modifying artist viewer to use artist's uri instead of albumartist's uri
Changes to be committed:
	modified:   src/js/services/google/middleware.js
	modified:   src/js/services/mopidy/middleware.js
	modified:   src/js/store/index.js

### CODE REVIEW

**Comment by jaedb** [comment]
Can you please provide background to this change? What is the need for this change, especially when the value can be changed in the UI, per user?
What are the consequences for how other people use Iris and manage their music libraries?
Typically a PR would be related to a feature request issue explaining these things.

**Comment by darkguinito** [comment]
Hello James, 

You right, it miss background a bit.

I use mopidy/Iris only with local files and i simply wanted to see the full list of artists.
After performing a local scan, i discover that more or less half of the artists scanned was missing.
I checked in the SQL-lite db and it seem than all artists are there.
I guess that the only thing missing was some ID3 tags on mp3 files.

As the db seem to be contain the full list of artist, i expected that iris do it as well.

I didn't know that this setting could be change from UI. I guess, you are talking about the artist library URI that can be set in the settings page ?

I try to changed it, but i was not able to figure out how to make it work.
Can you tell me where i'm wrong, i just change value to `local:directory?type=artist&role=artist`

But i'm a bit confused because it seem to me, that those values are hardcoded, can you correct me were i'm wrong ?
I think this could also be link to this issue from mopidy-local repository:  https://github.com/mopidy/mopidy-local/issues/18

If it is possible to change this setting from the UI, you can close and forget the PR and i apologize for my mistake

**Comment by jaedb** [comment]
I think you might find that you've stumbled upon a bug. When changing the setting in the UI (_Settings > Advanced > Library Artists URI_) and refreshing your browser, is your change retained?

**Comment by darkguinito** [comment]
You're right, apparently changes does not seem retained.

I will try to understand why and I will keep you inform.

**Comment by jaedb** [comment]
Thanks for your effort to create this code contribution. It has actually highlighted an oversight to consider the custom _Library URI_ settings in this string replacement, so it'll require a bit more work at my end.

**Pull request closed without merging**
