### PR TITLE
Fixed lyrics on tiny screens

### PR DESCRIPTION
**Pull request by kerkenit**
On my 7" touchscreen on the Raspberry Pi I can't use it to sing along. The lyrics are to small. This have small change fixed this issue.

# Before #
Schermafbeelding 4

# After #
Schermafbeelding 5

### CODE REVIEW

**Comment by jaedb** [comment]
When viewing on a mobile phone in portrait mode, I suspect this will have the reverse effect, no?

**Comment by kerkenit** [comment]
> When viewing on a mobile phone in portrait mode, I suspect this will have the reverse effect, no?

You are right. This could break the mobile. But I can only see it on my desktop when I put Safari or Chrome in mobile device mode. On my iPhone the lyrics won't be visible. It gave me a genius not found error. On my RPi it is shown. I checked this last update on my phone and the css isn't applied. On my RPi it is applied. 
IMG_3444

**Review by jaedb — CHANGES_REQUESTED** [review]
@kerkenit please review this PR; the only files changed is the compiled `mopidy_iris/static/app.css`. You will need to make changes to the source code (ie `src/sass/...`) for a valid PR.

**Comment by kerkenit** [comment]
> @kerkenit please review this PR; the only files changed is the compiled `mopidy_iris/static/app.css`. You will need to make changes to the source code (ie `src/sass/...`) for a valid PR.

I don't know what to do. I'm not using the function anymore because it's really distractive during work.

**Pull request closed without merging**
